# Raspberry Pi 4 (BCM2711)

CONFIG_TARGET_bcm27xx=y
CONFIG_TARGET_bcm27xx_bcm2711=y

# Partitions
CONFIG_TARGET_KERNEL_PARTSIZE=64
CONFIG_TARGET_ROOTFS_PARTSIZE=1024

# C Library
CONFIG_LIBC_USE_GLIBC=y

# RPi specific
CONFIG_PACKAGE_kmod-brcmfmac=y
CONFIG_PACKAGE_brcmfmac-firmware-43455-sdio=y
CONFIG_PACKAGE_kmod-sound-core=y
CONFIG_PACKAGE_kmod-usb-hid=y

# Include universal config
$(cat config/universal.conf 2>/dev/null || true)